name: Ejecutar Bot de Telegram
on:
  schedule:
    - cron: "0 4 * * *"  # Se ejecuta a las 4 AM UTC (12 AM hora de Cuba UTC-4)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          python bot.py &
          sleep 14400  # 4 horas (14400 segundos)
