name: Ejecutar Bot de Telegram gift 
on:
  workflow_dispatch: # Permite ejecución manual
  schedule:
    - cron: '' # Ejecuta cada 6 horas

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Ejecutar Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
